"""Using .msgpack files to rapidly generate Jones pupils

In this example, we will use the .msgpack files generated by saving the 
EAC models to disk, and re-generate the surface data for new wavelengths.

This makes the assumption that your rays take the same path through the system,
so this is only valid for systems with little-to-no chromatic aberration.

However, this is a good way to quickly generate Jones pupils without access
to a Windows machine or the CODE V models
"""

from hwo_pol.writing import read_model
import poke.plotting as plot
import numpy as np

# Start by reading in the models
model_folder = "EAC4"

# Read in the model
model = read_model(model_folder)
orig_wavelength = model.wavelengths[0]

# Construct a new set of wavelengths centered around the current wavelength
BANDPASS = 0.20
NUM_WVLS = 5
SHORT_WVL = orig_wavelength * (1 - BANDPASS/2)
LONG_WVL = orig_wavelength * (1 + BANDPASS/2)
bandpass = np.linspace(SHORT_WVL, LONG_WVL, NUM_WVLS)

# Append new wavelengths to the model
model.wavelengths = bandpass

# Copy rayfronts from the model into wavelength dict
for wvl in model.wavelengths:
    model.rayfronts[wvl] = model.rayfronts[orig_wavelength]
    model.rayfronts[wvl].wavelength = wvl

# Reconstruct the surface list
model.construct_surflist_by_wavelength()

# Now run the Jones Pupil computation
model.compute_jones_pupil_by_wavelength()

for wvl in model.wavelengths:
    plot.jones_pupil(model.rayfronts[wvl])
